app/urls.py
from app.views import *
from django.urls import path
app_name='app'
urlpatterns=[
    path('pinky/',pinky,name='pinky'),
]

app1/urls.py
from app1.views import *
from django.urls import path
app_name='app1'
urlpatterns=[
    path('sonu/',sonu,name='sonu'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('app1/', include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def pinky(request):
    return render(request,'pinky.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def sonu(request):
    return render(request,'sonu.html')

templates/pinky.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to pinky html page</h1>
        <a href="{% url 'app1:sonu' %}">navigator sonu page</a>
    </center>
</body>
</html>

templates/sonu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to sonu html page</h1>
        <a href="{% url 'app:pinky' %}">navigator pinky page</a>
    </center>
</body>
</html>